import { defineField, defineType } from "sanity";

export const book = defineType({
  name: "book",
  title: "Book",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "string",
    }),
     defineField({
      name: "coverImage",
      title: "Cover Image",
      type: "image",
      options: {
        hotspot: true,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "spineColor",
      title: "Spine Color",
      type: "string",
      description: "Hex color used for the book spine (extracted from cover)",
    }),
    defineField({
      name: "price",
      title: "Price",
      type: "number",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "pages",
      title: "Pages",
      type: "number",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "pubdate",
      title: "Publication Year",
      type: "number",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "genre",
      title: "Genre",
      type: "string",
      options: {
        list: [
          "Skáldsögur",
          "Glæpasögur",
          "Rómantík",
          "Fantasíur",
          "Vísindaskáldskapur",
          "Hrollvekja",
          "Spennusögur",
          "Sálfræðitryllir",
          "Sögulegar skáldsögur",
          "Erótík",
          "Þjóðsögur",
          "Fræðibækur",
          "Andleg málefni",
          "Barnabækur 1-3 ára",
          "Barnabækur 4-6 ára",
          "Barnabækur 7-9 ára",
          "Barnabækur 10-12 ára",
          "Ungmennabækur",
          "Klassískar bókmenntir",
          "Leikrit",
          "Ljóð",
          "Smásögur",
          "Sjálfshjálparbækur",
          "Ævisögur",
          "Íþróttir",
          "Hannyrðir",
          "Uppskriftabækur",
          "Óskáldað efni",
          "Myndasögur",
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 3,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "fullDescription",
      title: "Full Description",
      type: "text",
      rows: 8,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      of: [{ type: "string" }],
      options: {
        layout: "tags",
      },
    }),
  ],
});